### ISSUE TITLE
API Issue with lazy token delete

### ISSUE THREAD

**Issue by rimb05** [rarible/protocol#199] opened 2021-12-03 13:27 UTC
Trying to run multiple instances of the lazy delete command: 

https://ethereum-api.rarible.org/v0.1/doc#operation/deleteLazyMintNftAsset

results in the API changing the supply and Lazy supply to large random numbers.

Running one instance of this command seems to work fine, but if you set up multiple threads to simultaneously run this command, the API changes the supply numbers.

This results in tokens that are impossible to delete later.

The tokens are all ERC-721 lazy tokens.  The tokens all had a supply of 1 originally, but the API changed these to a large number.

**Comment by rimb05** [comment] 2021-12-03 13:29
Here is the command we use:

let signature = sigUtil.personalSign(wallet.key.privateKey, { data: "I would like to burn my " + tokenID + " item." });

await axios.post("https://ethereum-api.rarible.org/v0.1/nft/items/" + collection + ":" + tokenID + "/lazy/delete", 
       {
	"creators": [wallet.address],
	"signatures": [signature]
	}).then((response) => {
          console.log(response.data);
        });

**Comment by rimb05** [comment] 2021-12-03 13:30
We are now stuck, because we have several tokens in our collection that can't be deleted.  Can you please help us by removing all the tokens in our collection?

**Comment by bobwith2bees** [comment] 2021-12-04 16:27
uh.... - I may have tried a similar post request (or three) this morning causing three 500 service errors, before I stopped  (Rinkeby )

http://ethereum-api-staging.rarible.org/v0.1/nft/items/0xf565108F208136B1AffD55d19A6236b6b6b9786D:100306472579328457046349313808861179829241188424940308508612815057466251280386/lazy/delete

And now the collection is no longer showing any items.    https://rinkeby.rarible.com/collection/0xf565108F208136B1AffD55d19A6236b6b6b9786D

**Comment by bobwith2bees** [comment] 2021-12-04 18:57
If it helps root cause - I should mention the tokenId I was removing had an invalid URL for the image metata data tag.  If there is some cleanup logic that attempts to parse the image field  - I had the tokenURI format (/ipfs/<CID>), not the correct ipfs://ipfs/<CID>/

**Comment by evgenynacu** [comment] 2021-12-06 06:21
@bobwith2bees  do you experience any problems now? We fixed the issue right away on Friday and @rimb05  confirmed everything's fine

**Comment by evgenynacu** [comment] 2021-12-06 15:03
@bobwith2bees that's not that easy to empty the collection.
If the error can be reproduced now, it's better to fix it on our side and then you can burn items yourself

**Comment by bobwith2bees** [comment] 2021-12-06 15:08
@evgenynacu - Good to know.  It means I can test my delete function more ;-)  

Is there an easy way with the rarible website to debug a bit more?  

![2021-12-06_09-04-56](https://user-images.githubusercontent.com/81196211/144870077-d23bc480-b3b2-4ff2-a7a9-2e7ae2879e2f.jpg)

**Comment by evgenynacu** [comment] 2021-12-06 15:13
Burning lazy minted items is not available yet through UI, only using sdk.

Marketplace team has this task in the pipeline.

Pls, do test deleting from your side. We are ready to debug this if you give us an example. I think the most part of it was already fixed. So, if you face this now, let me know - will try to debug and check logs too

**Comment by bobwith2bees** [comment] 2021-12-06 15:32
Found the cause of the 500 service error response.   I had trailing }} from a badly replaced Postman variable.  Not sure what impact that had on your backend. 

```
{
"creators": ["0xDDc3739A733602F6A6d626E9D0758F0c3481C17F}}"],
"signatures": ["0xc8cc55a7ede926570049c3b44cb39c9211af27ee0e1ad704c335e9b7c2d8972718a84e9811c32cfbfd683e970dc8a04319b2a0cfacf9c67e64312beaf99b29e21b"]
}
```

Now getting a 400 bad request - because I was using the creator's ID not the collection owner's ID.    
Thank you for the breadcrumbs with the expected signature.  I'll work more on my delete function ;-)

**Comment by bobwith2bees** [comment] 2021-12-06 16:27
Docs  Question -  

Does this 400 error mean the signature for user 0xddc3739a733602f6a6d626e9d0758f0c3481c17f is incorrect? 

"Incorrect signature for 0xf565108f208136b1affd55d19a6236b6b6b9786d:0xddc3739a733602f6a6d626e9d0758f0c3481c17f000000000000000000000018"

I just wanted to verify that the collection owner, is not required to sign.  Because a different account owns the collection (0xf565108f208136b1affd55d19a6236b6b6b9786d) which is also mentioned in the error message.

Thanks,
-Bob

**Comment by evgenynacu** [comment] 2021-12-06 17:11
Here 400 means exactly that as I see

It's a public collection. Right?
Signature of the collection owner is not required. Only signature of a minter

**Comment by bobwith2bees** [comment] 2021-12-06 21:06
@evgenynacu Got it.  API returns 204 No Content with correct signature.    You also see this little icon on the collection page which is a nice touch.  Including it here for the next user and the docs team.

![2021-12-06_13-49-07](https://user-images.githubusercontent.com/81196211/144913240-5ac9e181-13d3-42d5-9a1d-4011c2467de8.jpg)

The team may a different bug to track the 500 service error due to the malformed creator parameter (trailing }} in the creator argument.   I still have the "can't fetch metadata" errors on the collection page.  Even after calling delete on all the token id's I could figure out.

**Comment by evgenynacu** [comment] 2021-12-07 07:32
@bobwith2bees  if you see weird "can't fetch metadata" pls tell us the links

**Comment by bobwith2bees** [comment] 2021-12-07 15:48
@evgenynacu The collection is now showing again.  It looks like they have all been restored, as if I didn't call delete on any of the tokens.  I assume it is safe to re-delete items from the collection using the proper API call ;-)

Let me know you need me to try and reproduce the error.  Otherwise I think we can close out this second delete endpoint issue.  Thanks

**Comment by evgenynacu** [comment] 2021-12-08 04:14
@bobwith2bees  I'm a little lost here frankly speaking )

Let's close this issue and fell free to open new one if you see unexpected behavior. Please, give all information about the case and steps to reproduce the error.

**Closed** 2021-12-08 04:14 UTC
Labels: bug, Tier 3
