### ISSUE TITLE
Burned token still appears with ability to place a bid

### ISSUE THREAD

**Issue by vicwtang** [rarible/protocol#351] opened 2022-05-13 18:51 UTC
This token https://rarible.com/token/0x6dc6f1ebd33ad874a596908b11618e6229828510:113277356295846663305716423985495022567090845171550585720498478269451112284161?tab=history
is recorded in rarible.com with a deleted = false, meaning this is burned.

However, the page does not indicate this is the case. The ... button only shows "Report" when viewed by the token creator. The Place a Bid button is enabled, and one can click it to access the Place a Bid pop up.

This page should NOT be accessible if the token is burned. Or the BURNED status should be clearly indicated and Place a Bid should not be enabled.

**Comment by bobwith2bees** [comment] 2022-05-13 20:08
@vicwtang  How did you burn the item?  From the blank history - is this a lazy minted NFT?   There was a discussion on this here: https://github.com/rarible/protocol/issues/199

I believe  'deleted = true' indicates the item has been "burned" - but in the case of lazy minting it is just delisted and never minted.

**Comment by vicwtang** [comment] 2022-05-21 22:12
Sorry for the late reply. I was focused on finding a way around the polygon
underpricing error.
Yes it is a lazy minted item. So it was deleted and never minted. The issue
still is that in either case, the token should not show (as its "deleted")
or show that it is deleted and not take offers?
Its really just a UI issue...I'd rather that it not appear, as it was an
error in minting on my part.

**Comment by eduardstal** [comment] 2022-06-03 10:18
Deleted/burned items are shown as burned by the quantity label “x0”.
We can’t hide deleted items since it’s a part of the history of the chain, users, etc. 

Nevertheless, we will look into disabling “place a bid” for deleted items.

**Comment by eduardstal** [comment] 2022-06-17 12:32
An update on this: 
`We can’t hide deleted items since it’s a part of the history of the chain, users, etc.`

The marketplace team has confirmed that for now, they will be working on showing deleted items at the bottom of the collection. 

In the near future, the option to hide burned items will be available as a user preference, and it will not be available collection-wide.

**Comment by vicwtang** [comment] 2022-06-17 16:10
That works. Thanks Eduard

**Comment by evgenynacu** [comment] 2023-11-30 10:44
Closing the issue
Feel free to reopen it if any help needed here

**Closed by evgenynacu** 2023-11-30 10:44 UTC
