### ISSUE TITLE
Odd order execution error when using smart contract accounts

### ISSUE THREAD

**Issue by santteegt** [rarible/protocol#148] opened 2021-10-27 22:52 UTC
Hey,

We're integrating Rarible as a DAOHaus boost to allow DAOs to create sell/bid orders through proposals that can execute arbitrary contract calls using a Gnosis Safe "Minion". Everything seems to work fine when encoding and creating/posting orders through the minion. However, when trying to fill/execute an order through the Rarible UI, the following error is being raised: `Execution reverted: ECDSA: invalid signature length`, which seems odd as the maker address is a Gnosis Safe account. This kind of exception should be raised only if the signer is an EOA account but we signed the order using the Safe & EIP1271.

Here's an example of a sell order listed by a Gnosis Safe (0x40fad45a745b8026c7a...0a14) that fails when someone tries to fill that order:

* Collectible: https://rinkeby.rarible.com/token/0xb2f2950721ea31f835e46d4d7e431dd7af765367:0
* Order metadata: https://ipfs.io/ipfs/QmYBWWTG55XJLCD7nhPWLqtWH2NUny9DtjwZ86ERWABidS

I built a stack trace of the possible path within the contracts that makes the transaction throw an exception:

- Break 1: https://github.com/rarible/protocol-contracts/blob/7ae346d2181d2ffad7ccf02fb613c6af940ba057/exchange-v2/contracts/ExchangeV2Core.sol#L40
- Break 2: https://github.com/rarible/protocol-contracts/blob/7ae346d2181d2ffad7ccf02fb613c6af940ba057/exchange-v2/contracts/ExchangeV2Core.sol#L94
- Break 3: https://github.com/rarible/protocol-contracts/blob/7ae346d2181d2ffad7ccf02fb613c6af940ba057/exchange-v2/contracts/OrderValidator.sol#L25 
- The ECDSA: invalid signature length error should appear only if the maker address is an EOA account
https://github.com/rarible/protocol-contracts/blob/7ae346d2181d2ffad7ccf02fb613c6af940ba057/exchange-v2/contracts/OrderValidator.sol#L32

And here's a stack trace of the possible path within your SDK:

- Fill order https://github.com/rarible/protocol-ethereum-sdk/blob/fbf66a7e3a82e3f25ca0a4135b21f590e1da4bfc/packages/protocol-ethereum-sdk/src/order/fill-order/index.ts#L28
- Send Tx https://github.com/rarible/protocol-ethereum-sdk/blob/fbf66a7e3a82e3f25ca0a4135b21f590e1da4bfc/packages/protocol-ethereum-sdk/src/order/fill-order/index.ts#L80
- Call `matchOrders` on ExchangeV2: https://github.com/rarible/protocol-ethereum-sdk/blob/cda44c0eb84be3b805f57a3926e7016f134eaf38/packages/protocol-ethereum-sdk/src/order/fill-order/rarible-v2.ts#L46
  - Here's where I think the issue resides. Might be a wrong assignment of the maker address on the Left order

**Comment by gawainb** [comment] 2021-10-29 20:54
@evgenynacu checking in to see if there is a PR associated with this fix

**Comment by eduardstal** [comment] 2021-10-30 02:22
We already fixed this in our contract. There is a PR waiting to be merged, will probably be done by Monday / Tuesday next week (first week of November)

**Comment by evgenynacu** [comment] 2021-11-02 13:30
@gawainb @santteegt can you try it on rinkeby?
Could you contact me on tg/discord?

**Comment by eduardstal** [comment] 2021-11-06 06:36
> We already fixed this in our contract. There is a PR waiting to be merged, will probably be done by Monday / Tuesday next week (first week of November)

Due to the huge fees that occurred with deploying this fix, it's been delayed for either Saturday (6th of Nov) or Monday (8th of Nov) deployment.

**Comment by eduardstal** [comment] 2021-11-08 17:51
This should be fixed now. Please check.

**Comment by gawainb** [comment] 2021-11-10 18:42
@eduardstal this issue can be closed. This has been fixed with recent updates and I've confirmed this will be shipped successfully on mainnet soon.

**Closed** 2021-11-10 21:10 UTC
Labels: bug, Tier 3, Issue owner not responding
