### ISSUE TITLE
Polygon collection contract not working

### ISSUE THREAD

**Issue by braxxaz** [rarible/protocol#315] opened 2022-04-04 19:14 UTC
I created an ERC1155 contract on Rarible about 17 days and for some reason I cant add it nor it shows up in my collections but if i do a search of the contracts/collection name in rarible it shows up but I still cant use it.

Contract: https://polygonscan.com/address/0xd7196d9b12924abd27f6fd7047e4e8e53af64ae7
Contract in Rarible saying it belongs to Rarible and not me:
https://rarible.com/collection/polygon/0xd7196d9b12924abd27f6fd7047e4e8e53af64ae7/items

Wallet: 0xD38faF91516ed0f180912ec88Aa253FF01750128

![contract 1](https://user-images.githubusercontent.com/88421270/161615519-dca51f14-f347-4938-a82f-d132126e0dda.png)
![contract 2](https://user-images.githubusercontent.com/88421270/161615528-51571a2a-0709-4db2-98be-fa083b984d7f.png)
![contract 3](https://user-images.githubusercontent.com/88421270/161615530-31ec7065-e40c-48a4-a247-e3a50b97a56f.png)

**Comment by bobwith2bees** [comment] 2022-04-08 21:43
This is a duplicate of https://github.com/rarible/protocol/issues/301 which was marked fixed last week.

**Comment by hanzel98** [comment] 2022-04-08 22:05
I'm trying to import my collection deployed on Polygon, but I'm getting this error. The contract was imported with no issues on Opensea, but Rarible doesn't allow me to import it. Does anyone here know why is this happening? Or maybe do you know how to correctly import in Rarible a collection deployed on polygon?
This is the contract on Polygonscan, I'm the collection owner and I'm logged in with the owner account:
https://polygonscan.com/address/0x0f80e081e04d952a7f90ca7be29b223d25ee26cc?fbclid=IwAR2eilH-jhcyErOt2sHiaHmq6n4ETMCd1gTZ_kpHvSjSLWmdWhY9urTyYgs

<img width="1512" alt="Screen Shot 2022-04-08 at 3 38 19 PM" src="https://user-images.githubusercontent.com/33629234/162538134-9d4651c1-a5e5-4a4a-a1e0-bd46810c57b8.png">

**Comment by eduardstal** [comment] 2022-04-11 09:54
Hey @braxxaz @bobwith2bees & @hanzel98. We'll investigate this; it seems the initial bug report in #301 didn't fix it.

**Comment by TtheBC01** [comment] 2022-04-18 18:11
same thing for me, still persisting

**Comment by braxxaz** [comment] 2022-04-29 15:37
Thank you it got fixed now but I still can't verify none of the contracts

**Comment by eduardstal** [comment] 2022-05-13 16:28
Closing this. 

Also @braxxaz, the last time our team tried to verify a contract created with our factories, it didn't work due to the fact that we are using beacon proxies. It's very hard to verify contracts.

**Closed by eduardstal** 2022-05-13 16:28 UTC
Labels: rarible.com marketplace
