### ISSUE TITLE
Missing metadata in Ethereum get items bulk API 

### ISSUE THREAD

**Issue by vaultec81** [rarible/protocol#310] opened 2022-04-01 16:54 UTC
We have been using the Ethereum Items API to get a list of owned items of an address. Specifically ```https://ethereum-api.rarible.org/v0.1/nft/items/byOwner?owner=0xbf72b541c7750be800cb92eb460d8e59f4942e72```. The API returns a list of NFT Ids and a set of basic information. The metadata attribute is diagramed in the docs, but it is not returned from the API. The metadata is completely missing, which includes title, description, image/media, attributes, etc.

This issue also applies to other APIs such as byCollection, byIds. 

Below I have attached some screenshots of missing metadata from the API

![itemsByOwner](https://user-images.githubusercontent.com/47548474/161301217-28858915-8662-429c-9436-15704aac2617.png)
![itemsByIds](https://user-images.githubusercontent.com/47548474/161301223-defa68df-4040-46bd-91c5-023f30262832.png)

**Comment by eduardstal** [comment] 2022-04-06 17:50
This bug seems to only affect the `ethereum-api`.  I will be getting in touch with our team to clarify if we can provide any support such as bug fixes for API's that are not meant for production usage.

Multichain API works: 
https://api.rarible.org/v0.1/items/byOwner?owner=ETHEREUM:0xbf72b541c7750be800cb92eb460d8e59f4942e72&blockchains=ETHEREUM

**Comment by eduardstal** [comment] 2022-04-14 14:11
It seems this is not a bug. We will not be providing meta for this endpoint. Provided above you have the Multichain API endpoint that does the same thing & contains the meta you're looking for. 

Closing this for now.

**Closed by eduardstal** 2022-04-14 14:11 UTC
Labels: Tier 2 - in progress, API bug
