### ISSUE TITLE
NFT metadata not showing on Rinkeby

### ISSUE THREAD

**Issue by iboxgithub** [rarible/protocol#161] opened 2021-11-11 17:39 UTC
Hi everyone, the NFT below: 
`https://rinkeby.rarible.com/token/0x9e63dbccee84fcdd0e210340bfa0e3dc67566acb:5?tab=details `
doesnt pull the metadata on Rinkeby, is it normal? @eduardstal suggested it might be related to the Indexer on Discord

I checked the SC on etherscan (Rinkeby) 
`https://rinkeby.etherscan.io/address/0x9e63dbCCeE84FCdd0E210340BFa0e3Dc67566aCb#readContract
`
and the URI is correct
`ipfs://QmUdNQ63os5Gdh4FLfnsZ2CL2tKuQ8NRkRnwkNsJCETS9B/5.json`

thanks for your help!

**Comment by chusla** [comment] 2021-11-11 17:44
having a similar issue with recently created tokens via SDK only.  render on rinkeby.rarible but not OS for some reason, has been over 48 hours so does not look to be an opensea rendering queue issue:

https://rinkeby.rarible.com/token/0x6ede7f3c26975aad32a475e1021d8f6f39c89d82:23682216723492589668510415302253876416785786327849593973156745954918236422150?tab=details

https://testnets.opensea.io/assets/0x6ede7f3c26975aad32a475e1021d8f6f39c89d82/23682216723492589668510415302253876416785786327849593973156745954918236422150

![image](https://user-images.githubusercontent.com/90009543/141344364-207e419f-268b-48b1-82c3-7b4f005d42b3.png)


A token I created in similar timeframe using old direct API calls has rendered correctly, leading me to believe this is something related to the SDK.

https://testnets.opensea.io/assets/0x6ede7f3c26975aad32a475e1021d8f6f39c89d82/3939678908558661877700378542264120479129353372516953395555235114166104621153

if there is the chance this is OS related, whom can we reach out to for them to check what is going on?  Thanks!

**Comment by evgenynacu** [comment] 2021-11-11 18:16
Thanks guys, will check tomorrow

**Comment by chusla** [comment] 2021-11-12 19:26
hi @eduardstal @evgenynacu can we get an update for this issue on call?  thanks!

**Comment by eduardstal** [comment] 2021-11-12 19:33
Eugene suspects Incorrect URI's are sent to the contract. We will update token contracts for this, possibly early next week. The front end will be fixed today.

**Comment by bobwith2bees** [comment] 2021-11-12 19:38
Please document what exactly is wrong for future readers of the thread.

Incorrect URI: 
Correct URI:

And it sound like there is a workaround being rolled out, so does that mean the Incorrect and Correct will both be supported moving forward?   Just looking for the preferred / most compatible format to use for future NFTs. 

Preferred URI format going forward (to be used in documentation):

**Comment by iboxgithub** [comment] 2021-11-15 14:03
aligned with @bobwith2bees cause some of my contracts actually work, so I would really like to understand what went wrong here

**Comment by evgenynacu** [comment] 2021-11-16 10:41
Hey guys
I see some different issues here
1. From the initial post: https://rinkeby.rarible.com/token/0x9e63dbccee84fcdd0e210340bfa0e3dc67566acb:5?tab=details As I see, here everything's fine from the contract point of view. uri is correct, that's on us, we'll take care
2. from @chusla : https://github.com/rarible/protocol/issues/161#issuecomment-966496412

In 2nd I see, uri is not correct (that's why opensea doesn't show it correctly)
This can be caused by base uri (it's applied as prefix to uri sent to the contract).
Also, in the latest sdk we added checks. It will throw an error if incorrect uri is sent to sdk

For example, if base uri is ipfs:/ (as is in many our contracts), then users can mint with uris only starting with ipfs:/
If uri doesn't start with base uri, then SDK will throw an error

**Comment by iboxgithub** [comment] 2021-11-16 11:06
thanks @evgenynacu , I am only interested by [1] (I wonder if point [2] does not deserve a dedicated ticket)
-> as this is also an issue with OpenSea would you be able to let them know, or detail here, what happened?

**Comment by inartin** [comment] 2021-11-16 12:30
I did a test with **ipfs://** prefix and seems like it did fix the issue for OpenSea and now only the issue from the initial post remains.

**Comment by evgenynacu** [comment] 2021-11-22 09:02
As I see, initial post is working good too now.

Regarding issues with OpenSea: you used uri as ipfs hash.
This means, contract doesn't return correct uri for specific token:

![image](https://user-images.githubusercontent.com/439188/142832376-291da99f-563a-4a89-89f1-87cb6460a737.png)

So, 
1. you need to use correct uri when lazy minting (result uri should be 'ipfs://QmeNHYyA3oKhrHrKVUpaVLFZd39KNPjHJV9yipDHmCmrrd' or 'ipfs://ipfs/QmeNHYyA3oKhrHrKVUpaVLFZd39KNPjHJV9yipDHmCmrrd') 

2. This was improved in the latest SDK: now it will throw error immediately if you try to mint with incorrect uri

**Closed by evgenynacu** 2021-11-22 09:02 UTC
Labels: bug, collection-indexing, Tier 3
